[seaweed-nodes]
seaweedfs-node ansible_host=192.168.56.101 ansible_ssh_private_key_file=~/.ssh/seaweed_lab/key_seaweed

[trino-nodes]
trino-sea-node ansible_host=192.168.56.102 ansible_ssh_private_key_file=~/.ssh/seaweed_lab/key_trino

[k8s-nodes]
k8s-node ansible_host=192.168.56.103 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/seaweed_lab/key_k8s

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'