[storage]
seaweedfs-node ansible_host=192.168.56.101 ansible_ssh_private_key_file=/home/ericson/.ssh/seaweed_lab/key_seaweed

[compute]
trino-sea-node ansible_host=192.168.56.102 ansible_ssh_private_key_file=/home/ericson/.ssh/seaweed_lab/key_trino

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'