---
- name: "Postgres : Instalar PostgreSQL"
  apt:
    name: postgresql
    state: present
  become: yes

- name: "Postgres : Garantir que o serviço está rodando"
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: "postgres : Criar diretório tmp para execução remota do Ansible"
  file:
    path: /var/lib/postgresql/.ansible/tmp
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: yes

- name: "Postgres : Criar banco de dados para o Hive Metastore"
  become: yes
  become_user: postgres
  postgresql_db:
    name: metastore

- name: "Postgres : Criar usuário 'hive' com permissões"
  become: yes
  become_user: postgres
  no_log: true
  postgresql_user:
    db: metastore
    name: hive
    password: hive_password
    priv: "ALL"

- name: "Postgres : Configurar acesso externo (necessário para o HMS)"
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: "host    metastore       hive            192.168.56.0/24         md5"
    insertafter: EOF
  become: yes
  notify: "restart postgres"

- name: "Postgres : Escutar em todas as interfaces"
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?listen_addresses ="
    line: "listen_addresses = '*'"
  become: yes
  notify: "restart postgres"