---
- name: "Configuração da Infraestrutura de Dados"
  hosts: all
  become: yes
  roles:
    - role: common
      tags: common

- name: "Configuração do Storage e Catálogo (VM 1)"
  hosts: seaweed-nodes
  become: yes
  roles:
    - role: postgres
      tags: postgres
    - role: seaweed
      tags: seaweed
    - role: hive
      tags: hive

- name: "Configuração do Motor de Consulta (VM 2)"
  hosts: trino-nodes
  become: yes
  roles:
    - role: trino
      tags: trino

- name: "Configuração do Nó Kubernetes (VM 3)"
  hosts: k8s-nodes
  become: yes
  roles:
    - role: k8s-seaweed-csi
      tags: k8s-seaweed-csi